[package]
name = "rust-testing"
version = "0.1.0"
authors = ["Fikayo <fikfikky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
